name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Generate data
        run: |
          mkdir -p data/raw
          python data_gen/simulate_events.py --days 14 --members 8000 --titles 400
      - name: Run pipeline
        env:
          DBT_PROFILES_DIR: dbt_project
        run: python orchestration/flow.py
      - name: Lint
        run: flake8
